import { createMaterializedProjectContext } from './project-context-schema.mjs';

function formatList(label, values) {
  return values?.length ? `- ${label}: ${values.join(', ')}` : `- ${label}: Not detected`;
}

export function materializeProjectContextMemories({ projectSlug, detected, declared, updatedAt }) {
  const commonTags = ['project-context', `project:${projectSlug}`];

  return [
    createMaterializedProjectContext({
      kind: 'stack-runtime',
      title: 'Project stack and runtime',
      summary: `Languages: ${detected.stack.languages.join(', ')}. Frameworks: ${detected.stack.frameworks.join(', ')}.`,
      body: [
        formatList('Languages', detected.stack.languages),
        formatList('Runtimes', detected.stack.runtimes),
        formatList('Frameworks', detected.stack.frameworks),
        formatList('Package managers', detected.stack.packageManagers),
      ].join('\n'),
      tags: [...commonTags, 'stack'],
      sourceFiles: ['package.json', 'tsconfig.json'],
      graphRefs: [],
      sourceMode: 'detected',
      confidence: 'high',
      updatedAt,
    }),
    createMaterializedProjectContext({
      kind: 'dependencies-summary',
      title: 'Dependency summary',
      summary: `Critical dependencies: ${(detected.stack.dependenciesSummary.critical ?? []).join(', ') || 'none'}.`,
      body: [formatList('Critical', detected.stack.dependenciesSummary.critical), formatList('Testing', detected.stack.dependenciesSummary.testing)].join('\n'),
      tags: [...commonTags, 'dependencies'],
      sourceFiles: ['package.json'],
      graphRefs: [],
      sourceMode: 'detected',
      confidence: 'high',
      updatedAt,
    }),
    createMaterializedProjectContext({
      kind: 'integrations-summary',
      title: 'Integration summary',
      summary: `Detected services: ${(detected.stack.integrations.detectedServices ?? []).join(', ') || 'none'}.`,
      body: formatList('Services', detected.stack.integrations.detectedServices),
      tags: [...commonTags, 'integrations'],
      sourceFiles: ['src'],
      graphRefs: [],
      sourceMode: 'detected',
      confidence: 'medium',
      updatedAt,
    }),
    createMaterializedProjectContext({
      kind: 'architecture-current',
      title: 'Current architecture',
      summary: `Pattern: ${detected.architecture.pattern}. Entry points: ${(detected.architecture.entryPoints ?? []).join(', ') || 'none'}.`,
      body: [
        `- Pattern: ${detected.architecture.pattern}`,
        formatList('Entry points', detected.architecture.entryPoints),
      ].join('\n'),
      tags: [...commonTags, 'architecture', 'current-state'],
      sourceFiles: detected.architecture.entryPoints,
      graphRefs: detected.architecture.graphRefs,
      sourceMode: 'detected',
      confidence: 'medium',
      updatedAt,
    }),
    createMaterializedProjectContext({
      kind: 'architecture-target',
      title: 'Target architecture',
      summary: declared.architectureTarget.architecture || 'No target architecture declared.',
      body: declared.architectureTarget.architecture || 'No target architecture declared.',
      tags: [...commonTags, 'architecture', 'target-state'],
      sourceFiles: ['.planning/project-memory-context/project-context/declared/architecture-target.json'],
      graphRefs: [],
      sourceMode: 'declared',
      confidence: 'high',
      updatedAt,
    }),
    createMaterializedProjectContext({
      kind: 'structure-summary',
      title: 'Project structure summary',
      summary: `Root directories: ${(detected.structure.rootDirectories ?? []).join(', ') || 'none'}.`,
      body: [formatList('Root directories', detected.structure.rootDirectories), formatList('Key subtrees', detected.structure.keySubtrees), formatList('Entry points', detected.structure.entryPoints)].join('\n'),
      tags: [...commonTags, 'structure'],
      sourceFiles: detected.structure.entryPoints,
      graphRefs: [],
      sourceMode: 'detected',
      confidence: 'high',
      updatedAt,
    }),
    createMaterializedProjectContext({
      kind: 'technical-rules',
      title: 'Technical rules',
      summary: [...(declared.technicalRules.rules ?? []), ...(detected.rules.rules ?? [])].slice(0, 2).join(' '),
      body: [...(declared.technicalRules.rules ?? []), ...(detected.rules.rules ?? [])].map((line) => `- ${line}`).join('\n'),
      tags: [...commonTags, 'rules'],
      sourceFiles: ['README.md'],
      graphRefs: [],
      sourceMode: 'merged',
      confidence: 'medium',
      updatedAt,
    }),
    createMaterializedProjectContext({
      kind: 'project-requirements',
      title: 'Project requirements',
      summary: (declared.projectRequirements.requirements ?? []).slice(0, 2).join(' '),
      body: (declared.projectRequirements.requirements ?? []).map((line) => `- ${line}`).join('\n') || '- No declared requirements.',
      tags: [...commonTags, 'requirements'],
      sourceFiles: ['.planning/project-memory-context/project-context/declared/project-requirements.json'],
      graphRefs: [],
      sourceMode: 'declared',
      confidence: 'high',
      updatedAt,
    }),
    createMaterializedProjectContext({
      kind: 'known-issues-and-fixes',
      title: 'Known issues and fixes',
      summary: `${(declared.knownIssuesAndFixes.items ?? []).length} known issues recorded.`,
      body: (declared.knownIssuesAndFixes.items ?? []).map((item) => `- Symptom: ${item.symptom}; Workaround: ${item.workaround}`).join('\n') || '- No known issues recorded.',
      tags: [...commonTags, 'issues'],
      sourceFiles: ['.planning/project-memory-context/project-context/declared/known-issues-and-fixes.json'],
      graphRefs: [],
      sourceMode: 'declared',
      confidence: 'high',
      updatedAt,
    }),
  ];
}
