// Generated by pmc install — do not edit. Re-run `pmc init .` to regenerate.
// Thin wrapper: OpenCode auto-loads this file from .opencode/plugins/ and the
// real implementation lives in the installed PMC package.
export const PMCPlugin = async (input) => {
  try {
    const mod = await import('{{PMC_PLUGIN_IMPORT}}');
    return await mod.PMCPlugin(input);
  } catch {
    // PMC unavailable (moved/uninstalled package): never break OpenCode startup.
    return {};
  }
};
